// <auto-generated />
using DataAccess;
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SocialDbContext))]
    partial class SocialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {

            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618


            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("User"); 

                entity.HasKey(e => e.Id); 

                entity.Property(e => e.Id)
                      .ValueGeneratedOnAdd();  

                entity.Property(e => e.Dni)
                      .IsRequired();

                entity.Property(e => e.Name)
                      .HasMaxLength(200)
                      .IsUnicode(true);

                entity.Property(e => e.lastName)
                      .HasMaxLength(200)
                      .IsUnicode(true);

                entity.Property(e => e.DateOfBirth)
                      .IsRequired()
                      .HasColumnType("datetime");

                entity.Property(e => e.Email)
                      .HasMaxLength(255)
                      .IsUnicode(true);

                entity.Property(e => e.GenderId)
                      .IsRequired();

                entity.Property(e => e.CountryId)
                      .IsRequired();
            });
        }
    }
}
